#!/bin/bash
###############################################################################
# 8_OA_AS PRD .env 생성 스크립트
#
# AWS SSM Parameter Store에서 시크릿을 가져와 .env 파일을 자동 생성.
# Jenkins 배포 파이프라인에서 PRD 배포 시 자동 실행 가능.
#
# 사전 조건:
#   1. EC2에 IAM Role 또는 AWS CLI 설정 (ssm:GetParametersByPath 권한)
#   2. Parameter Store에 /oaas/prd/* 파라미터 등록 완료
#
# 사용법:
#   ./generate-env.sh prd /app/oaas/standalone/.env
#   ./generate-env.sh dev /app/oaas/standalone/.env
###############################################################################

set -euo pipefail

ENV=${1:-prd}
ENV_FILE=${2:-/app/oaas/standalone/.env}
AWS_REGION=${3:-ap-northeast-2}
PARAM_PREFIX="/oaas/${ENV}"

echo "=========================================="
echo "  8_OA_AS .env Generator"
echo "  Environment : ${ENV}"
echo "  Output      : ${ENV_FILE}"
echo "  Param Prefix: ${PARAM_PREFIX}"
echo "=========================================="

echo ">>> Fetching parameters from SSM Parameter Store..."
PARAMS=$(aws ssm get-parameters-by-path \
    --path "${PARAM_PREFIX}" \
    --with-decryption \
    --recursive \
    --region "${AWS_REGION}" \
    --query "Parameters[*].{Name:Name,Value:Value}" \
    --output json 2>/dev/null)

if [ -z "$PARAMS" ] || [ "$PARAMS" = "[]" ]; then
    echo "ERROR: No parameters found at ${PARAM_PREFIX}"
    echo "Please register parameters in AWS SSM Parameter Store first."
    exit 1
fi

# 기존 .env 백업
if [ -f "${ENV_FILE}" ]; then
    BACKUP="${ENV_FILE}.bak.$(date +%Y%m%d_%H%M%S)"
    cp "${ENV_FILE}" "${BACKUP}"
    echo ">>> Existing .env backed up to ${BACKUP}"
fi

# .env 파일 생성 - 고정값 + Parameter Store 값
mkdir -p "$(dirname "${ENV_FILE}")"
cat > "${ENV_FILE}" << 'STATIC_EOF'
# =============================================================================
# 8_OA_AS Environment (Auto-generated by deploy/generate-env.sh)
# DO NOT EDIT MANUALLY - Managed by AWS SSM Parameter Store
# =============================================================================

# Next.js standalone
NODE_ENV=production
PORT=3000
HOSTNAME=0.0.0.0
NEXT_TELEMETRY_DISABLED=1

# OpenAI 임베딩 (이름 지정만, 키는 SSM에서)
OPENAI_EMBEDDING_MODEL=text-embedding-3-small

# AWS Region (SES / S3 공통)
AWS_REGION=ap-northeast-2
STATIC_EOF

echo "" >> "${ENV_FILE}"
echo "# --- SSM Parameter Store (${PARAM_PREFIX}) ---" >> "${ENV_FILE}"

echo "$PARAMS" | python3 -c "
import json, sys
params = json.load(sys.stdin)
for p in params:
    # /oaas/prd/DATABASE_URL -> DATABASE_URL
    key = p['Name'].split('/')[-1]
    value = p['Value']
    print(f'{key}={value}')
" >> "${ENV_FILE}"

chmod 600 "${ENV_FILE}"

# 심볼릭 링크: PM2 cwd에서 .env 접근용
SYMLINK_PATH="/app/oaas/.env"
if [ ! -L "${SYMLINK_PATH}" ]; then
    ln -sf "${ENV_FILE}" "${SYMLINK_PATH}"
    echo ">>> Created symlink: ${SYMLINK_PATH} -> ${ENV_FILE}"
fi

echo ">>> .env generated successfully with $(grep -c '=' ${ENV_FILE}) variables"
echo ">>> File permissions: $(ls -la ${ENV_FILE} | awk '{print $1}')"
